---
- name: error handlign concept
  hosts: all
  tasks:
    - block:
       - name: install git on ubuntu servers
         apt:
           name: git
           state: present
           update_cache: yes
      rescue:
        - name: install git on redhat
          yum:
            name: git
            state: present
            update_cache: yes
...
