---
- name: installing os on dif servers
  hosts: ubuntu
  tasks:
    - name: install git
      apt:
        name: git
        state: present
        update_cache: yes
- name: installing git on redhat servers
  hosts: Redhat
  tasks:
   - name: install git on redhat
     yum:
      name: git
      state: present
      update_cache: yes
...
