---
- name: configure tomcat
  hosts: all
  tasks: 
    - name: install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cahce: yes
    - name: install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present

    - name: copy customised users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: replcae the port number from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restart the tomcat
      service:
        name: tomcat10
        state: restarted

    - name: check tomact on service module
      uri:
        url: "http://172.31.17.240:9090"
        state_caode: 200
...














