---
- name: creating a users
  hosts: servers
  tasks: 

     - name: user creation 
       user: 

         name: Dummy
         password: 6689
         uid: 88899
         comment: 'a super user'
         
      
...
