- name: implementing tags
  hosts: jenkinservers, webserver, slaveserver
  gather_facts: false
  become: yes
  tasks:
    - name: install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags:
        - tree_installation
        - always
    - name: create user
      user:
        name: uddhbad
        password: udhab123
      tags: user_creation
    - name: copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
...

