---
- name: create a suer and change th permssion accordignly 
  hosts: all
  tasks: 
     - name: create a user
       user: 
          name: aalu
          password: aaalu123
          uid: 8778
          comment: "a normal user"
     - name: copy file one to another destination 
       copy: 
           src: /etc/passwd
           dest: /tmp/aalu

     - name: changing permission on th files
       file:
          name: /tmp/aalu
          state: touch
          mode: 666
          owner: aalu
          group: root
...
